name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Push the Docker image
      run: | 
        echo "${{ secrets.DOCKER_PW }}" | docker login -u "aminalaakom" --password-stdin
        docker image build -t aminalaakom/bitcoin:latest .
        docker push aminalaakom/bitcoin:latest
        
        
        
        
        
        
        
      
